name: Download and Deploy

on:
  push:
    branches:
      - main  # 您的分支名称
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download Excel.zip
        run: |
          python download_excel.py --env_file ./ba.env --output_file ./BAJPAkpSrc/Excel.zip

      - name: Commit and push Excel.zip
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BAJPAkpSrc.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # 如果 BAJPAkpSrc 目录已存在，先删除
          if [ -d "BAJPAkpSrc" ]; then
            rm -rf BAJPAkpSrc
          fi

          # 克隆目标仓库
          git clone "$TARGET_REPO_URL" BAJPAkpSrc
          cd BAJPAkpSrc

          # 添加 Excel.zip 文件
          git add Excel.zip
          git commit -m "Download and deploy" || echo "No changes to commit."
          git push origin
