name: Update Files

on:
  workflow_dispatch:  # 仅允许手动触发

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run setup_flatdata.py to generate FlatData
        run: |
          python setup_flatdata.py

      - name: Download ExcelDB.db and unpack it
        run: |
          python download_files.py --env_file ./ba.env --output_dir ./downloads --temp_dir ./temp

      - name: Check file size and skip if over 50MB
        run: |
          MAX_SIZE=52428800  # 50MB in bytes
          for file in ./temp/*.json; do
            if [ -f "$file" ]; then
              filesize=$(stat -c%s "$file")
              if [ "$filesize" -gt "$MAX_SIZE" ]; then
                echo "File $file is larger than 50MB. Skipping."
                rm "$file"  # 删除超过大小限制的文件
              fi
            fi
          done

      - name: Commit and push generated files
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BAJPApkSrc.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone "$TARGET_REPO_URL" BAJPApkSrc
          cp -r ./temp/*.json BAJPApkSrc/ExcelDB/原版/

          cd BAJPApkSrc
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Update"
            git push origin
          fi
