name: Download and Deploy

on:
  push:
    branches:
      - main  # 您的分支名称
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Clone target repository
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BAJPAkpSrc.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          # 如果 BAJPAkpSrc 目录已存在，先删除
          if [ -d "BAJPAkpSrc" ]; then
            rm -rf BAJPAkpSrc
          fi
          # 克隆目标仓库
          git clone "$TARGET_REPO_URL" BAJPAkpSrc

      - name: Download Excel.zip
        run: |
          python download_excel.py --env_file ./ba.env --output_file ./BAJPAkpSrc/Excel.zip
          # 检查文件是否下载成功
          if [ ! -f "./BAJPAkpSrc/Excel.zip" ]; then
            echo "Error: Excel.zip file not found after download."
            exit 1
          fi

      - name: Commit and push
        run: |
          cd BAJPAkpSrc
          git add Excel.zip
          git commit -m "Update Excel.zip" || echo "No changes to commit."
          git push origin
