name: Download and Deploy

on:
  push:
    branches:
      - main  # 您的分支名称
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Clone target repository
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BAJPApkSrc.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone "$TARGET_REPO_URL" BAJPAkpSrc

      - name: Download Excel.zip
        run: |
          python download_excel.py --env_file ./ba.env --output_file ./BAJPAkpSrc/Excel.zip

      - name: Commit and push
        run: |
          cd BAJPAkpSrc
          git add Excel.zip
          git commit -m "Update Excel.zip" || echo "No changes to commit."
          git push origin
