name: Deploy File

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region to deploy (jp,cn,gl or comma-separated combination)'
        required: false
        default: 'all'
        type: string
  push:
    paths:
      - 'ba.env'
  repository_dispatch:
    types: [run-deployment]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Parse deployment trigger
        id: parse-trigger
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            MESSAGE="${{ github.event.client_payload.regions }}"
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MESSAGE="${{ inputs.region }}"
          else
            MESSAGE="all"
          fi
          
          MESSAGE=$(echo "$MESSAGE" | tr '[:upper:]' '[:lower:]')
          echo "message=${MESSAGE}" >> $GITHUB_ENV
          echo "Detected regions: ${MESSAGE}"

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run JP tasks if requested
        if: contains(env.message, 'jp') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "Running JP tasks..."
          python -m regions.JP.setup_flatdata || echo "JP setup_flatdata failed, continuing..."
          python -m regions.JP.download_files --env_file ./ba.env --output_dir ./downloads || echo "JP download_files failed, continuing..."
          python -m unpack_excel_db --db_path ./downloads/ExcelDB.db --output_dir ./unpacked --flatbuffers_dir ./Extracted/FlatData --zip_path ./unpacked/日服原版DB.zip || echo "JP unpack_excel_db failed, continuing..."

      - name: Run CN tasks if requested
        if: contains(env.message, 'cn') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "Running CN tasks..."
          python -m regions.CN.setup_flatdata_cn || echo "CN setup_flatdata failed, continuing..."
          python -m regions.CN.download_files_cn --env_file ./ba.env --output_dir ./downloads || echo "CN download_files failed, continuing..."
          python -m unpack_excel_db --db_path ./downloads/ExcelDB.db --output_dir ./unpacked --flatbuffers_dir ./Extracted/FlatData --zip_path ./unpacked/国服原版DB.zip || echo "CN unpack_excel_db failed, continuing..."

      - name: Run GL tasks if requested
        if: contains(env.message, 'gl') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "Running GL tasks..."
          python -m regions.GL.setup_flatdata_gl || echo "GL setup_flatdata failed, continuing..."
          python -m regions.GL.download_files_gl --env_file ./ba.env --output_dir ./downloads || echo "GL download_files failed, continuing..."
          python -m unpack_excel_db --db_path ./downloads/ExcelDB.db --output_dir ./unpacked --flatbuffers_dir ./Extracted/FlatData --zip_path ./unpacked/国际服原版DB.zip || echo "GL unpack_excel_db failed, continuing..."

      - name: Commit and push generated files
        continue-on-error: true
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Assets-TableBundles.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone "$TARGET_REPO_URL" BA-Assets-TableBundles
          cp -r ./unpacked/*.zip BA-Assets-TableBundles/

          cd BA-Assets-TableBundles
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Update"
            git push origin
          fi
