name: Update Files

on:
  workflow_dispatch:  # 仅允许手动触发

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Generate FlatData
        run: |
          if [ -f setup_flatdata.py ]; then
            python setup_flatdata.py
          fi

      - name: Download and unpack ExcelDB
        run: |
          if [ -f download_files.py ]; then
            python download_files.py --env_file ./ba.env --output_dir ./downloads --temp_dir ./temp
          fi

      - name: Prepare files for commit
        id: prepare_files
        run: |
          # 创建目标目录结构
          mkdir -p staging/ExcelDB/原版/
          
          # 检查并复制不超过50MB的JSON文件
          echo "Checking file sizes..."
          for file in ./temp/*.json; do
            if [ -f "$file" ]; then
              filesize=$(stat -c%s "$file")
              if [ $filesize -lt 52428800 ]; then  # 50MB in bytes
                cp "$file" staging/ExcelDB/原版/
                echo "✅ Copied $(basename "$file") ($((filesize/1024/1024))MB)"
              else
                echo "⚠️  Skipping $(basename "$file") - $((filesize/1024/1024))MB exceeds limit"
              fi
            fi
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 配置git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 克隆目标仓库到新目录
          if [ -d "target_repo" ]; then
            rm -rf target_repo
          fi
          git clone https://github.com/beichen23333/BAJPApkSrc.git target_repo
          
          # 复制准备好的文件
          if [ -d "staging" ]; then
            echo "Copying files to target repository..."
            cp -r staging/* target_repo/
          fi
          
          # 提交变更
          cd target_repo
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
            echo "Changes pushed successfully"
          fi
