name: Update Files

on:
  workflow_dispatch:  # 仅允许手动触发

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run setup_flatdata.py to generate FlatData
        run: |
          python setup_flatdata.py

      - name: Download ExcelDB.db and Excel.zip
        run: |
          python download_files.py --env_file ./ba.env --output_dir ./downloads

      - name: Unpack ExcelDB.db and generate JSON files
        run: |
          python unpack_excel_db.py --db_path ./downloads/ExcelDB.db --output_dir ./unpacked --flatbuffers_dir ./Extracted/FlatData --zip_path ./unpacked/日服原版DB.zip

      - name: Check file size and skip if over 100MB
        run: |
          MAX_SIZE=$((100 * 1024 * 1024))  # 100MB in bytes
          for file in ./unpacked/*.json; do
            if [ -f "$file" ]; then
              filesize=$(stat -c%s "$file")
              if [ "$filesize" -gt "$MAX_SIZE" ]; then
                echo "File $file is larger than 100MB. Skipping."
                rm "$file"  # 删除超过大小限制的文件
              fi
            fi
          done

      - name: Commit and push generated files
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BAJPAkpSrc.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone "$TARGET_REPO_URL" BAJPAkpSrc
          cp -r ./unpacked/*.zip BAJPAkpSrc/

          cd BAJPAkpSrc
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "Update"
            git push origin
          fi
