name: Download and Deploy Excel.zip

on:
  push:
    branches:
      - main  # 您的分支名称
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download Excel.zip
        run: |
          python download_excel.py --env_file ./ba.env --output_file ./Excel.zip

      - name: Commit and push Excel.zip
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Excel.zip
          git commit -m "Download and deploy Excel.zip" || echo "No changes to commit."
          git push https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/beichen23333/BA-Chinese-Translation.git main
