name: 反序列化部署

on:
  workflow_dispatch:
    inputs:
      region:
        description: '选择要部署的服务器（jp,cn,gl）'
        required: false
        default: 'all'
        type: string
  repository_dispatch:
    types: [run-deployment]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 获取消息
        id: parse-trigger
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            MESSAGE="${{ github.event.client_payload.regions }}"
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            MESSAGE="${{ inputs.region }}"
          else
            MESSAGE="all"
          fi
          
          MESSAGE=$(echo "$MESSAGE" | tr '[:upper:]' '[:lower:]')
          echo "message=${MESSAGE}" >> $GITHUB_ENV
          echo "Detected regions: ${MESSAGE}"

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 克隆仓库到临时目录
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Chinese-Translation-A.git temp-repo

      - name: 合并内容到当前目录
        run: |
          rsync -a --remove-source-files temp-repo/ ./
          rm -rf temp-repo

      - name: 运行日服反序列化
        if: contains(env.message, 'jp') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "运行日服反序列化..."
          python -m regions.JP.setup_flatdata || echo "生成日服FL..."
          python -m regions.JP.download_files --env_file ./ba.env --output_dir ./downloads || echo "日服文件下载..."
          python -m unpack_excel_db \
            --db_path ./downloads/ExcelDB.db \
            --output_dir ./unpacked \
            --flatbuffers_dir ./Extracted/FlatData \
            --server 日服 \
            --config_file 配置.json \
          echo "日服处理完成"

      - name: 运行国服反序列化
        if: contains(env.message, 'cn') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "运行国服反序列化..."
          python -m regions.JP.setup_flatdata || echo "国服存在加密，无法生成dump.cs，生成日服FL..."
          python -m regions.CN.download_files_cn --env_file ./ba.env --output_dir ./downloads || echo "国服文件下载..."
          python -m unpack_excel_db \
            --db_path ./downloads/ExcelDB.db \
            --output_dir ./unpacked \
            --flatbuffers_dir ./Extracted/FlatData \
            --server 国服 \
            --config_file 配置.json \
          echo "国服处理完成"

      - name: 运行国际服反序列化
        if: contains(env.message, 'gl') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "运行国际服反序列化..."
          python -m regions.GL.setup_flatdata_gl || echo "生成国际服FL..."
          python -m regions.GL.download_files_gl --env_file ./ba.env --output_dir ./downloads || echo "国际服文件下载..."
          python -m unpack_excel_db \
            --db_path ./downloads/ExcelDB.db \
            --output_dir ./unpacked \
            --flatbuffers_dir ./Extracted/FlatData \
            --server 国际服 \
            --config_file 配置.json \
          echo "国际服处理完成"

      - name: 提交变更
        continue-on-error: true
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Assets-TableBundles.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone "$TARGET_REPO_URL" BA-Assets-TableBundles
          cp -r ./unpacked/*.zip BA-Assets-TableBundles/
          cd BA-Assets-TableBundles
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi

      - name: 触发部署
        if: contains(env.message, 'jp') || env.message == 'all'
        continue-on-error: true
        run: |
          echo "::group::正在触发部署"
          curl -sS -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{
              "event_type": "Back",
              "client_payload": {
                "regions": "'过滤'",
                "source": "auto-updater",
                "timestamp": "'$(date -u +"%FT%TZ")'"
              }
            }'
          echo "Curl 退出代码: $?"
          echo "::endgroup::"
          echo "部署触发成功"
