name: Deploy to Private Repository

on:
  push:
    branches:
      - main  # 您的分支名称
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果您有依赖文件

      - name: Run script
        run: |
          python build_excel_zip.py --excel_input_path ./Excel.zip --repl_input_dir ./Excel --temp_output_dir ./temp_output

      - name: Deploy to Private Repository
        env:
          TARGET_REPO_URL: https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BAJPApkSrc.git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone "$TARGET_REPO_URL" BAJPApkSrc
          cd BAJPApkSrc  # 进入克隆的仓库目录
          cp -r ../temp_output/* .  # 将 temp_output 内的文件复制到克隆的仓库目录
          git add .  # 添加所有文件
          git commit -m "Deploy" || echo "No changes to commit."  # 提交更改
          git push origin main  # 推送到目标仓库的 main 分支
