name: 过滤同步与替换

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: '配置文件路径'
        required: false
        default: '配置.json'
        type: string
      filter:
        description: '是否过滤新的文本？'
        required: false
        type: boolean
        default: false
      ba_env_path1:
        description: '版本读取路径1（新版本）'
        required: false
        default: 'ba.env'
        type: string
      ba_env_path2:
        description: '版本读取路径2（旧版本）'
        required: false
        default: 'BA-Assets-TableBundles/ba.env'
        type: string
      ba_env_path2:
        description: '过滤后的文件移动路径'
        required: false
        default: 'BA-Text/日服'
        type: string
      sync:
        description: '是否同步国服文本？'
        required: false
        type: boolean
        default: false
      sync2:
        description: '是否同步国际服文本？'
        required: false
        type: boolean
        default: false
      replace:
        description: '是否写回汉化文本？'
        required: false
        type: boolean
        default: false
      hanhua_dir:
        description: '汉化后文本存放路径'
        required: false
        default: 'BA-Text/汉化后'
        type: string
      rizip_path:
        description: '文本存放路径读取（zip路径）'
        required: false
        default: 'BA-Text/日服.zip'
        type: string
      rizip_path2:
        description: '文本存放路径写回（zip路径）'
        required: false
        default: 'BA-Text/日服.zip'
        type: string
      modify:
        description: '是否全局替换预设文本？'
        required: false
        type: boolean
        default: false
      rules:
        description: '替换规则路径'
        required: false
        default: '替换名词.txt'
        type: string
      out_zip:
        description: '替换读取路径（zip路径）'
        required: false
        default: 'BA-Text/日服.zip'
        type: string
      out_zip2:
        description: '替换写出路径（zip路径）'
        required: false
        default: 'BA-Text/日服.zip'
        type: string
      modify2:
        description: '是否单独替换预设文本？'
        required: false
        type: boolean
        default: false
      rules2:
        description: '替换规则路径'
        required: false
        default: '特殊修改.json'
        type: string
      out_zip:
        description: '替换读取路径（zip路径）'
        required: false
        default: 'BA-Text/日服.zip'
        type: string
      out_zip2:
        description: '替换写出路径（zip路径）'
        required: false
        default: 'BA-Text/日服.zip'
        type: string
  repository_dispatch:
    types: [Back]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          echo "依赖安装完成"

      - name: 克隆仓库
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Assets-TableBundles.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Chinese-Translation-A.git temp-repo

      - name: 合并内容到当前目录
        run: |
          rsync -a --remove-source-files temp-repo/ ./
          rm -rf temp-repo

      - name: 运行过滤（写出新的文本）
        if: ${{ inputs.filter || github.event_name == 'repository_dispatch' }}
        run: |
          python compare.py

      - name: 运行同步（同步国服国际服文本）
        if: ${{ inputs.sync }}
        run: |
          python replace/replace.py

      - name: 运行替换（写回汉化后文本）
        if: ${{ inputs.replace }}
        run: |
          python replace/back.py

      - name: 运行替换2（对部分文本单独修改）
        if: ${{ inputs.modify }}
        run: |
          python replace/replace2.py

      - name: 提交过滤文件
        if: ${{ inputs.filter || github.event_name == 'repository_dispatch' }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi
          cd ..

      - name: 提交ba.env
        if: ${{ inputs.filter || github.event_name == 'repository_dispatch' }}
        run: |
          cp -r ba.env BA-Assets-TableBundles/
          cd BA-Assets-TableBundles
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi

      - name: 触发部署
        if: ${{ inputs.filter || github.event_name == 'repository_dispatch' }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "DeepSeek"}'
