name: Update Yostart Server URL
on:
  workflow_dispatch:
    inputs:
      DeployFlatData:
        description: 'Deploy FlatData？'
        required: false
        type: boolean
        default: true
      UsePresetFlatData:
        description: 'Use preset FlatData？'
        required: false
        type: boolean
        default: false
      Extract:
        description: 'Extract new text？'
        required: false
        type: boolean
        default: true
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 2

      - name: Setup python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Update server
        run: python update_urls.py ba.env server-info.json

      - name: Check if ba.env was modified
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ba.env
          if git diff --cached --quiet; then
            echo "No updates detected, skip the submission."
            echo "update_detected=false" >> $GITHUB_ENV
          else
            echo "Detected a URL update for the Yostart server, updating the ba.env sever address..."
            echo "update_detected=true" >> $GITHUB_ENV
            git commit -m "Updata Yostart URL"
            git push origin HEAD
          fi

      - name: Clone repositories
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-FlatData.git

      - name: Process FlatData
        id: flatdata
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: |
          if [[ "${{inputs.UsePresetFlatData}}" == "true" ]]; then
            echo "Use preset FlatData..."
            echo "flatbuffers_dir=./BA-FlatData/" >> $GITHUB_OUTPUT
            echo "should_commit_flatdata=false" >> $GITHUB_OUTPUT
          else
            echo "Use local FlatData..."
            echo "flatbuffers_dir=./Extracted/FlatData" >> $GITHUB_OUTPUT
            echo "should_commit_flatdata=true" >> $GITHUB_OUTPUT
          fi

      - name: Get version
        id: get-versions
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: bash version.sh ba.env >> "$GITHUB_OUTPUT"

      - name: Get JP FlatData
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: |
          python setup_flatdata.py

      - name: Get JP ExcelDB and ExcelTable
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: |
          python download_files.py --env_file ./ba.env --output_dir ./downloads

      - name: Unpack ExcelDB and ExcelTable
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: |
          python unpack_excel.py --db_path ./downloads/ExcelDB.db --zip_path ./downloads/Excel.zip --output_dir ./unpacked --flatbuffers_dir ${{steps.flatdata.outputs.flatbuffers_dir}} --config_file 配置.json --output_zip ./日服${{steps.get-versions.outputs.BA_VERSION_NAME}}.zip

      - name: Committing FlatData
        if: ${{env.update_detected || inputs.DeployFlatData}}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          cd ./Extracted/FlatData/
          zip -j "FlatData${BA_VERSION_NAME}.zip" *.py
          mv "FlatData${BA_VERSION_NAME}.zip" ../../BA-FlatData/
          cd ../../BA-FlatData
          git add "FlatData${BA_VERSION_NAME}.zip"
          cd

          if git diff-index --quiet HEAD; then
            echo "Skip committing."
          else
            git commit -m "Committing."
            git push origin
          fi

      - name: Committing zip
        if: ${{env.update_detected && steps.flatdata.outputs.should_commit_flatdata}}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cp -r ./*.zip BA-Text/ || { echo "::warning::Failed to copy the zip file. Zip not found. Continue to run the subsequent commands."; }
          cd BA-Text
          git add .
          cd

          if git diff-index --quiet HEAD; then
            echo "Skip committing."
          else
            git commit -m "Committing."
            git push origin
          fi

      - name: Deploy Extract
        if: ${{inputs.Extract}}
        run: |
          curl -sS -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{
              "event_type": "Extract",
              "client_payload": {
                "source": "auto-updater",
                "timestamp": "'$(date -u +"%FT%TZ")'"
              }
            }'