name: Update Yostar Server URL

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update_urls.py with ba.env
        run: |
          python update_urls.py ba.env server-info.json

      - name: Check if ba.env was modified
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ba.env
          if git diff --cached --quiet; then
            echo "没有检测到更新，跳过提交"
            echo "update_detected=false" >> $GITHUB_ENV
          else
            echo "检测到悠星服务器URL更新，正在更新ba.env网址..."
            echo "update_detected=true" >> $GITHUB_ENV
          fi

      - name: Push updated server info JSON to current repository
        if: env.update_detected == 'true'
        run: |
          git add server-info.json
          git commit -m "更新悠星服务器URL"
          git push origin HEAD

      - name: Trigger Deploy Workflow
        if: env.update_detected == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"repository_dispatch_type":"DEPLOY_TRIGGER"}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches/repository_dispatch
