name: Update Yostar Server URL

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 2

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update_urls
        run: |
          python -m regions.JP.update_urls ba.env server-info.json

      - name: Run update_urls_cn
        run: |
          python -m regions.CN.CN_run ba.env server-info.json

      - name: Run update_urls_gl
        run: |
          python -m regions.GL.GL_run ba.env server-info.json

      - name: Check ba.env changes and detect regions
        id: check-changes
        run: |
          echo "Checking for changes in ba.env..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ba.env
          
          if git diff --cached --quiet; then
            echo "No changes detected in ba.env"
            echo "update_detected=false" >> $GITHUB_ENV
          else
            echo "Changes detected in ba.env, analyzing modified lines..."
            echo "update_detected=true" >> $GITHUB_ENV
            
            # 获取所有变动的行号
            changed_lines=$(git diff --cached --unified=0 ba.env | grep '^+' | grep -v '^\+\+\+' | cut -d: -f1 | sort -nu)
            echo "Changed line numbers: ${changed_lines}"
            
            # 初始化区域标志
            jp_changed=false
            cn_changed=false
            gl_changed=false
            
            # 检查每个变动的行属于哪个区域
            for line in $changed_lines; do
              echo "Checking line $line"
              if [[ $line -ge 1 && $line -le 4 ]]; then
                echo "Line $line belongs to JP region"
                jp_changed=true
              elif [[ $line -ge 5 && $line -le 8 ]]; then
                echo "Line $line belongs to CN region"
                cn_changed=true
              elif [[ $line -ge 9 && $line -le 12 ]]; then
                echo "Line $line belongs to GL region"
                gl_changed=true
              fi
            done
            
            # 构建消息
            message_parts=()
            $jp_changed && message_parts+=("jp")
            $cn_changed && message_parts+=("cn")
            $gl_changed && message_parts+=("gl")
            
            message=$(IFS=,; echo "${message_parts[*]}")
            echo "Detected changes in regions: ${message}"
            echo "message=${message}" >> $GITHUB_ENV
          fi

      - name: Commit changes if detected
        if: env.update_detected == 'true'
        run: |
          git commit -m "Update server URLs"
          git push origin HEAD
          echo "Changes committed successfully"

      - name: Trigger Deploy Workflow
        if: env.update_detected == 'true'
        env:
          MESSAGE: ${{ env.message }}
        run: |
          echo "Triggering deployment for regions: ${MESSAGE}"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "run-deployment", "client_payload": {"message": "'"${MESSAGE}"'"}}'
          echo "Deployment trigger sent successfully"
