name: 同步

on:
  workflow_dispatch:
    inputs:
      sync:
        description: '是否同步国服文本？'
        required: false
        type: boolean
        default: true
      sync2:
        description: '是否同步国际服文本？'
        required: false
        type: boolean
        default: true
      env_file:
        description: 'ba.env存放路径'
        required: true
        default: 'ba.env'
        type: string
      config_path:
        description: '配置存放路径'
        required: true
        default: '配置.json'
        type: string
      read_zip:
        description: '文本zip读取路径'
        required: true
        default: 'BA-Text/日服.zip'
        type: string
      out_zip:
        description: '文本zip写出路径'
        required: true
        default: 'BA-Text/日服.zip'
        type: string

  repository_dispatch:
    types: [同步]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install zhconv
          echo "依赖安装完成"

      - name: 克隆仓库
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Assets-TableBundles.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Chinese-Translation-A.git temp-repo

      - name: 移动指定文件到当前目录
        run: |
          cp BA-Text/替换名词.txt ./
          cp BA-Text/汉化名词.txt ./
          cp BA-Text/特殊修改.json ./
          cp BA-Text/配置.json ./

      - name: 合并内容到当前目录
        run: |
          rsync -a --remove-source-files temp-repo/ ./
          rm -rf temp-repo

      - name: 获取版本号
        id: get_version
        run: |
          bash .github/scripts/get_version_name.sh "${{ inputs.env_file }}" >> "$GITHUB_OUTPUT"

      - name: 运行同步
        if: ${{ inputs.sync || inputs.sync2 }}
        run: |
          python tool/sync.py --sync "${{ inputs.sync }}" --sync2 "${{ inputs.sync2 }}" --config_path "${{ inputs.config_path }}" --read_zip "${{ inputs.read_zip }}" --out_zip "${{ inputs.out_zip }}" --ba_version_name "${{ steps.get_version.outputs.BA_VERSION_NAME }}" --ba_version_name_cn "${{ steps.get_version.outputs.BA_VERSION_NAME_CN }}" --ba_version_name_gl "${{ steps.get_version.outputs.BA_VERSION_NAME_GL }}"

      - name: 提交过滤文件
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi
          cd ..
