name: 翻译（4）

on:
  workflow_dispatch:
    inputs:
      input_dir:
        description: '读取文件路径'
        required: true
        default: 'BA-Text/日服'
        type: string
      terms_path:
        description: '汉化名称路径'
        required: true
        default: '汉化名词.txt'
        type: string
      output_dir:
        description: '输出文件路径'
        required: true
        default: 'BA-Text/翻译'
        type: string
      config_path:
        description: '配置文件路径'
        required: true
        default: '配置.json'
        type: string
      batch_size:
        description: '单次翻译数量'
        required: true
        default: '40'
        type: string
      max_workers:
        description: '线程数量'
        required: true
        default: '7'
        type: string
  repository_dispatch:
    types: [翻译]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 克隆仓库
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Chinese-Translation-A.git temp-repo

      - name: 移动指定文件到当前目录
        run: |
          cp BA-Text/替换名词.txt ./
          cp BA-Text/汉化名词.txt ./
          cp BA-Text/特殊修改.json ./
          cp BA-Text/配置.json ./

      - name: 合并内容到当前目录
        run: |
          rsync -a --remove-source-files temp-repo/ ./
          rm -rf temp-repo

      - name: 运行汉化
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          KIMI_API_KEY: ${{ secrets.KIMI_API_KEY }}
        run: |
          python tool/translation.py --input_dir "${{ inputs.input_dir }}" --terms_path "${{ inputs.terms_path }}" --output_dir "${{ inputs.output_dir }}" --config_path "${{ inputs.config_path }}" --batch_size "${{ inputs.batch_size }}" --max_workers "${{ inputs.max_workers }}"

      - name: 提交汉化文件
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi
