name: 自动合并（合并Excel和DB）

on:
  workflow_dispatch:
    inputs:
      env_path:
        description: '版本号读取路径'
        required: true
        default: 'ba.env'
        type: string

  repository_dispatch:
    types: [合并]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 克隆仓库
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Assets-TableBundles.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Chinese-Translation-A.git temp-repo

      - name: 移动指定文件到当前目录
        run: |
          cp BA-Text/替换名词.txt ./
          cp BA-Text/汉化名词.txt ./
          cp BA-Text/特殊修改.json ./
          cp BA-Text/配置.json ./

      - name: 合并内容到当前目录
        run: |
          rsync -a --remove-source-files temp-repo/ ./
          rm -rf temp-repo

      - name: 获取新版本号
        id: new_ver
        run: |
          bash .github/scripts/get_version_name.sh "${{ inputs.env_path }}" >> "$GITHUB_OUTPUT"

      - name: 运行合并
        run: |
          python tool/合并.py --new_version "${{ steps.new_ver.outputs.BA_VERSION_NAME }}"

      - name: 提交合并文件
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi
          cd ..

      - name: 触发部署
        run: |
          curl -sS -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{
              "event_type": "更新版本",
              "client_payload": {
                "source": "auto-updater",
                "timestamp": "'$(date -u +"%FT%TZ")'"
              }
            }'