name: 过滤

on:
  workflow_dispatch:
    inputs:
      env_path1:
        description: '新版本版本号读取路径'
        required: true
        default: 'ba.env'
        type: string
      env_path2:
        description: '旧版本版本号读取路径'
        required: true
        default: 'BA-Assets-TableBundles/ba.env'
        type: string
      out_path:
        description: '过滤后的文件写出路径'
        required: true
        default: 'BA-Text/日服'
        type: string
      new:
        description: '是否提交新的ba.env？'
        required: true
        type: boolean
        default: true
      deploy:
        description: '是否部署DeepSeek翻译？'
        required: true
        type: boolean
        default: true
  repository_dispatch:
    types: [过滤]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 克隆仓库
        run: |
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Assets-TableBundles.git
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Chinese-Translation-A.git temp-repo
          git clone https://x-access-token:${{ secrets.APK_SRC_REPO }}@github.com/beichen23333/BA-Text.git temp-ba-text

      - name: 移动指定文件到当前目录
        run: |
          mv temp-ba-text/替换名词.txt ./
          mv temp-ba-text/汉化名词.txt ./
          mv temp-ba-text/特殊修改.json ./
          mv temp-ba-text/配置.json ./
          rm -rf temp-ba-text

      - name: 合并内容到当前目录
        run: |
          rsync -a --remove-source-files temp-repo/ ./
          rm -rf temp-repo

      - name: 运行过滤
        run: |
          python tool/compare.py --env_path1 "${{ inputs.env_path1 }}" --env_path2 "${{ inputs.env_path2 }}" --out_path "{{ inputs.out_path }}"

      - name: 提交过滤文件
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd BA-Text
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi
          cd ..

      - name: 提交ba.env
        if: ${{ inputs.new }}
        run: |
          cp -r ba.env BA-Assets-TableBundles/
          cd BA-Assets-TableBundles
          git add .
          if git diff-index --quiet HEAD; then
            echo "无更改，跳过提交文件"
          else
            git commit -m "提交文件"
            git push origin
          fi

      - name: 触发部署
        if: ${{ inputs.deploy }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "DeepSeek"}'
